version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - nakedret
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wastedassign
    - copyloopvar

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: error

output:
  formats:
    text:
      path: stdout